modLoader="javafml" #mandatory
loaderVersion="[24,)" #mandatory (24 is current forge version)
updateJSONURL="https://github.com/Direwolf20-MC/BuildingGadgets/raw/master/update.json" #optional
issueTrackerURL="https://github.com/Direwolf20-MC/BuildingGadgets/issues" #optional
displayURL="https://diresbg.com/" #optional
credits="The Forge and FML guys, McJty, Vazkii, CPW, and Pahimar for helping me learn java/forge modding.  Rorax for the textures!" #optional
authors="Direwolf20" #The man himself
[[mods]] #mandatory
modId="buildinggadgets" #mandatory
version="2.99.0" #mandatory
displayName="Building Gadgets" #mandatory
description='''Adds some gadgets to help you build!
Building and Exchanging Gadget offer basic building & exchanging functionality for easily creating walls/columns etc.
The Destruction Gadget will help you clear out large Areas for your complex builds which you can Copy and Paste at will with the Copy-Paste Gadget!
'''

## A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.buildinggadgets]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[24,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="BEFORE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"